openapi: 3.0.0
info:
  title: Enroll API
  version: 1.0.0
paths:
  /enrolls:
    post:
      summary: Crear un nuevo registro de inscripción
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostEnroll'
      responses:
        '201':
          description: Inscripción creada con éxito
  /enrolls/{id}/alumn:
    put:
      summary: Actualizar datos del alumno
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Alumn'
      responses:
        '204':
          description: Datos del alumno actualizados correctamente
  /enrolls/{id}/familysituation:
    put:
      summary: Actualizar situación familiar
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                files:
                  type: array
                  items:
                    type: string
                    format: binary
                  description: Archivos relacionados con la situación familiar
              required:
                - files
      responses:
        '204':
          description: Situación familiar actualizada
  /enrolls/{id}/mother:
    put:
      summary: Actualizar datos de la madre
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Mother'
      responses:
        '204':
          description: Datos de la madre actualizados
  /enrolls/{id}/father:
    put:
      summary: Actualizar datos del padre
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Father'
      responses:
        '204':
          description: Datos del padre actualizados
  /enrolls/{id}/other:
    put:
      summary: Actualizar otros datos
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                school_insurance:
                  type: array
                  items:
                    type: string
                    format: binary
                  description: Archivos relacionados con el seguro escolar
                ampa:
                  type: array
                  items:
                    type: string
                    format: binary
                  description: Archivos relacionados con la AMPA
                school_transportation:
                  type: array
                  items:
                    type: string
                    format: binary
                  description: Archivos relacionados con el transporte escolar
              required:
                - school_insurance
      responses:
        '204':
          description: Otros datos actualizados
  /enrolls/{id}/health:
    put:
      summary: Actualizar datos de salud
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                condition1:
                  type: boolean
                  description: Condición 1
                  default: false
                condition2:
                  type: boolean
                  description: Condición 2
                  default: false
                condition3:
                  type: boolean
                  description: Condición 3
                  default: false
                condition4:
                  type: boolean
                  description: Condición 4
                  default: false
                files:
                  type: array
                  items:
                    type: string
                    format: binary
                  description: Archivos relacionados con el estado de salud
              required:
                - condition1
                - condition2
                - condition3
                - condition4
      responses:
        '204':
          description: Datos de salud actualizados
  /enrolls/{id}/confirm:
    put:
      summary: Confirmar datos
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Confirm'
      responses:
        '204':
          description: Confirmación realizada

components:
  schemas:
    PostEnroll:
      type: object
      properties:
        identity:
          type: string
          enum: [student, mother, father, guardian]
        situation:
          type: string
          enum: [single, married, divorced, widowed]
          nullable: true
        custody:
          type: string
          enum: [mother, father, both]
          nullable: true
        parentalAuthority:
          type: string
          enum: [mother, father, both]
          nullable: true
        student:
          type: object
          properties:
            email:
              type: string
              format: email
            phone:
              type: string
          required: [email, phone]
        mother:
          type: object
          properties:
            dni_observe:
              type: string
              format: binary
              description: DNI observado, imagen requerida
            dni_reverse:
              type: string
              format: binary
              description: DNI invertido, imagen requerida
          required: [dni_observe, dni_reverse]
        father:
          type: object
          properties:
            dni_observe:
              type: string
              format: binary
              description: DNI observado, imagen requerida
            dni_reverse:
              type: string
              format: binary
              description: DNI invertido, imagen requerida
          required: [dni_observe, dni_reverse]
        guardian:
          type: object
          properties:
            email:
              type: string
              format: email
              nullable: true
            phone:
              type: string
              nullable: true
          required: []
    Alumn:
      type: object
      properties:
        nre:
          type: string
        dni_observe:
          type: string
          format: binary
        dni_reverse:
          type: string
          format: binary
        academic_record:
          type: array
          items:
            type: string
            format: binary
        healthcards_observe:
          type: string
          format: binary
        healthcards_reverse:
          type: string
          format: binary
      required:
        - nre
        - dni_observe
        - dni_reverse
        - healthcards_observe
        - healthcards_reverse
    FilesArray:
      type: array
      items:
        type: string
        format: binary
      description: Archivos relacionados con situaciones o registros.
    SchoolData:
      type: object
      properties:
        school_insurance:
          type: array
          items:
            type: string
            format: binary
          description: Archivos relacionados con el seguro escolar
        ampa:
          type: array
          items:
            type: string
            format: binary
          description: Archivos relacionados con la AMPA
        school_transportation:
          type: array
          items:
            type: string
            format: binary
          description: Archivos relacionados con el transporte escolar
      required: []
    Mother:
      type: object
      properties:
        dni_observe:
          type: string
          format: binary
        dni_reverse:
          type: string
          format: binary
      required:
        - dni_observe
        - dni_reverse
    Father:
      type: object
      properties:
        dni_observe:
          type: string
          format: binary
        dni_reverse:
          type: string
          format: binary
      required:
        - dni_observe
        - dni_reverse
    Health:
      type: object
      properties:
        condition1:
          type: boolean
          description: Condición 1
          default: false
        condition2:
          type: boolean
          description: Condición 2
          default: false
        condition3:
          type: boolean
          description: Condición 3
          default: false
        condition4:
          type: boolean
          description: Condición 4
          default: false
        files:
          type: array
          items:
            type: string
            format: binary
          description: Archivos relacionados con el estado de salud
      required:
        - condition1
        - condition2
        - condition3
        - condition4
    Confirm:
      type: object
      properties:
        information:
          type: boolean
          description: Campo para aceptar la información, por defecto es true

